# -----------------------------------------------------------------------------
# Versions
# -----------------------------------------------------------------------------
[versions]

agp = "9.3.1"
jdk = "17"
minSdk = "24"
compileSdk = "37"
targetSdk = "36"
sourceCompatibility = "17"
targetCompatibility = "17"

activityCompose = "1.13.0"
androidxKotlinCompiler = "1.5.0"
appcompat = "1.7.1"
composeBom = "2026.06.01"
coreKtx = "1.19.0"
espressoCore = "3.7.0"
hilt = "2.60.1"
jetbrainsKotlinJvm = "2.4.10"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.4.10"
ksp = "2.3.11"
lifecycleRuntimeKtx = "2.11.0"
navigationCompose = "2.9.8"

# -----------------------------------------------------------------------------
# Libraries
# -----------------------------------------------------------------------------
[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# Test
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
compose-compiler-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

# -----------------------------------------------------------------------------
# Bundles
# -----------------------------------------------------------------------------
[bundles]
androidx-compose = [
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-bom",
    "androidx-compose-material3",
    "androidx-activity-compose",
]
test = [
    "junit",
    "androidx-junit",
    "androidx-compose-ui-test-manifest",
    "androidx-compose-ui-test-junit4",
    "androidx-espresso-core",
]

# -----------------------------------------------------------------------------
# Plugins
# -----------------------------------------------------------------------------
[plugins]
android-application-conventions = { id = "android-application-conventions" }
android-composable-application-conventions = { id = "android-composable-application-conventions" }
android-library-conventions = { id = "android-library-conventions" }
android-composable-library-conventions = { id = "android-composable-library-conventions" }
kotlin-library-conventions = { id = "kotlin-library-conventions" }

androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
jetbrainsKotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
